sonar.projectKey=yunomix2834_x-buttonmousecontrol
sonar.projectName=x-buttonmousecontrol
sonar.organization=yunomix280304
sonar.sources=crates
sonar.tests=crates
sonar.sourceEncoding=UTF-8

sonar.rust.lcov.reportPaths=lcov.info