# mouse -> key
#[[bindings]]
#source_type = "mouse"
#source = "left"
#target_type = "key"
#target = "f"
#action = "tap"
#
#[[bindings]]
#source_type = "mouse"
#source = "right"
#target_type = "key"
#target = "h"
#action = "tap"

# key -> mouse
[[bindings]]
source_type = "key"
source = "f1"
target_type = "mouse"
target = "left"
action = "tap"
mode = "replace"

#[[bindings]]
#source_type = "key"
#source = "f2"
#target_type = "mouse"
#target = "right"
#action = "tap"